<div class="container">
	<div class="row-fluid header">
		<h2>Motivation story #2</h2>
	</div>
	<br/><br/><br/><br/>
	<div class="row-fluid content">
		<p>In the early summer of 2004, I got a phone call from Steve Jobs. He had been scattershot friendly to me over the years, with occasional bursts of intensity, especially when he was launching a new product that he wanted on the cover of Time or featured on CNN, places where I’d worked. But now that I was no longer at either of those places, I hadn’t heard from him much. We talked a bit about the Aspen Institute, which I had recently joined, and I invited him to speak at our summer campus in Colorado. He’d be happy to come, he said, but not to be onstage. He wanted instead to take a walk so that we could talk.</p>

		<p>That seemed a bit odd. I didn’t yet know that taking a long walk was his preferred way to have a serious conversation. It turned out that he wanted me to write a biography of him. I had recently published one on Benjamin Franklin and was writing one about Albert Einstein, and my initial reaction was to wonder, half jokingly, whether he saw himself as the natural successor in that sequence. Because I assumed that he was still in the middle of an oscillating career that had many more ups and downs left, I demurred. Not now, I said. Maybe in a decade or two, when you retire.</p>

		<p>I had known him since 1984, when he came to Manhattan to have lunch with Time’s editors and extol his new Macintosh. He was petulant even then, attacking a Time correspondent for having wounded him with a story that was too revealing. But talking to him afterward, I found myself rather captivated, as so many others have been over the years, by his engaging intensity. We stayed in touch, even after he was ousted from Apple. When he had something to pitch, such as a NeXT computer or Pixar movie, the beam of his charm would suddenly refocus on me, and he would take me to a sushi restaurant in Lower Manhattan to tell me that whatever he was touting was the best thing he had ever produced. I liked him.</p>

		<p>When he was restored to the throne at Apple, we put him on the cover of Time, and soon thereafter he began offering me his ideas for a series we were doing on the most influential people of the century. He had launched his “Think Different” campaign, featuring iconic photos of some of the same people we were considering, and he found the endeavor of assessing historic influence fascinating.</p>

		<p>After I had deflected his suggestion that I write a biography of him, I heard from him every now and then. At one point I emailed to ask if it was true, as my daughter had told me, that the Apple logo was an homage to Alan Turing, the British computer pioneer who broke the German wartime codes and then committed suicide by biting into a cyanide-laced apple. He replied that he wished he had thought of that, but hadn’t. That started an exchange about the early history of Apple, and I found myself gathering string on the subject, just in case I ever decided to do such a book. When my Einstein biography came out, he came to a book event in Palo Alto and pulled me aside to suggest, again, that he would make a good subject.</p>

		<p>His persistence baffled me. He was known to guard his privacy, and I had no reason to believe he’d ever read any of my books. Maybe someday, I continued to say. But in 2009 his wife, Laurene Powell, said bluntly, “If you’re ever going to do a book on Steve, you’d better do it now.” He had just taken a second medical leave. I confessed to her that when he had first raised the idea, I hadn’t known he was sick. Almost nobody knew, she said. He had called me right before he was going to be operated on for cancer, and he was still keeping it a secret, she explained.</p>

		<p>I decided then to write this book. Jobs surprised me by readily acknowledging that he would have no control over it or even the right to see it in advance. “It’s your book,” he said. “I won’t even read it.” But later that fall he seemed to have second thoughts about cooperating and, though I didn’t know it, was hit by another round of cancer complications. He stopped returning my calls, and I put the project aside for a while.</p>

		<p>Then, unexpectedly, he phoned me late on the afternoon of New Year’s Eve 2009. He was at home in Palo Alto with only his sister, the writer Mona Simpson. His wife and their three children had taken a quick trip to go skiing, but he was not healthy enough to join them. He was in a reflective mood, and we talked for more than an hour. He began by recalling that he had wanted to build a frequency counter when he was twelve, and he was able to look up Bill Hewlett, the founder of HP, in the phone book and call him to get parts. Jobs said that the past twelve years of his life, since his return to Apple, had been his most productive in terms of creating new products. But his more important goal, he said, was to do what Hewlett and his friend David Packard had done, which was create a company that was so imbued with innovative creativity that it would outlive them.</p>
	</div>
</div>